<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta name="robots" content="noindex, nofollow">

    <meta name="description" content="">
    <meta name="author" content="1eye.io - John A Johnson (Andy)">

    <title>1eye.io control panel</title>
    
    <link rel='icon' href='favicon.ico'>

    <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>
    <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css'>

    <!--[if lt IE 9]>
        <script src='//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'></script>
        <script src='//oss.maxcdn.com/respond/1.4.2/respond.min.js'></script>
    <![endif]-->        
    
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,200' rel='stylesheet' type='text/css'>
    <style>
        body {
            background-color: #2B2B2B; 
        }
        
        * {
            font-family: 'Raleway', sans-serif;
            color: #FFF;
        }

        div h3 span {
            color : #FFF;
            font-size:14px;
        }

        div span {
            font-weight: 200;
        }

        h1 {
            font-weight: 200;
        }

        .login_box{
            background: #f32d27; /* Old browsers */
            /* IE9 SVG, needs conditional override of 'filter' to 'none' */
            background: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMTAwJSIgeDI9IjEwMCUiIHkyPSIwJSI+CiAgICA8c3RvcCBvZmZzZXQ9IjUlIiBzdG9wLWNvbG9yPSIjZjMyZDI3IiBzdG9wLW9wYWNpdHk9IjEiLz4KICAgIDxzdG9wIG9mZnNldD0iOTklIiBzdG9wLWNvbG9yPSIjZmY2YjQ1IiBzdG9wLW9wYWNpdHk9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==');
            background: -moz-linear-gradient(45deg,  #f32d27 5%, #ff6b45 99%); /* FF3.6+ */
            background: -webkit-gradient(linear, left bottom, right top, color-stop(5%,#f32d27), color-stop(99%,#ff6b45)); /* Chrome,Safari4+ */
            background: -webkit-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Chrome10+,Safari5.1+ */
            background: -o-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Opera 11.10+ */
            background: -ms-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* IE10+ */
            background: linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* W3C */
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f32d27', endColorstr='#ff6b45',GradientType=1 ); /* IE6-8 fallback on horizontal gradient */
            
            width:35%;
            min-width:400px;
            height:588px;
            margin: auto;

            -webkit-box-shadow: 0px 0px 8px 0px rgba(50, 50, 50, 0.54);
            -moz-box-shadow:    0px 0px 8px 0px rgba(50, 50, 50, 0.54);
            box-shadow:         0px 0px 8px 0px rgba(50, 50, 50, 0.54);
        }

        @media (max-width: 767px) {
            .login_box {
                background: #f32d27; /* Old browsers */
                /* IE9 SVG, needs conditional override of 'filter' to 'none' */
                background: url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDEgMSIgcHJlc2VydmVBc3BlY3RSYXRpbz0ibm9uZSI+CiAgPGxpbmVhckdyYWRpZW50IGlkPSJncmFkLXVjZ2ctZ2VuZXJhdGVkIiBncmFkaWVudFVuaXRzPSJ1c2VyU3BhY2VPblVzZSIgeDE9IjAlIiB5MT0iMTAwJSIgeDI9IjEwMCUiIHkyPSIwJSI+CiAgICA8c3RvcCBvZmZzZXQ9IjUlIiBzdG9wLWNvbG9yPSIjZjMyZDI3IiBzdG9wLW9wYWNpdHk9IjEiLz4KICAgIDxzdG9wIG9mZnNldD0iOTklIiBzdG9wLWNvbG9yPSIjZmY2YjQ1IiBzdG9wLW9wYWNpdHk9IjEiLz4KICA8L2xpbmVhckdyYWRpZW50PgogIDxyZWN0IHg9IjAiIHk9IjAiIHdpZHRoPSIxIiBoZWlnaHQ9IjEiIGZpbGw9InVybCgjZ3JhZC11Y2dnLWdlbmVyYXRlZCkiIC8+Cjwvc3ZnPg==');
                background: -moz-linear-gradient(45deg,  #f32d27 5%, #ff6b45 99%); /* FF3.6+ */
                background: -webkit-gradient(linear, left bottom, right top, color-stop(5%,#f32d27), color-stop(99%,#ff6b45)); /* Chrome,Safari4+ */
                background: -webkit-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Chrome10+,Safari5.1+ */
                background: -o-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* Opera 11.10+ */
                background: -ms-linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* IE10+ */
                background: linear-gradient(45deg,  #f32d27 5%,#ff6b45 99%); /* W3C */
                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f32d27', endColorstr='#ff6b45',GradientType=1 ); /* IE6-8 fallback on horizontal gradient */

                width:90%;
                min-width:370px;
                height:70%;
                margin: auto;

                -webkit-box-shadow: 0px 0px 8px 0px rgba(50, 50, 50, 0.54);
                -moz-box-shadow:    0px 0px 8px 0px rgba(50, 50, 50, 0.54);
                box-shadow:         0px 0px 8px 0px rgba(50, 50, 50, 0.54);
            }
        }

        .image-circle {
            border-radius: 50%;
            width: 175px;
            height: 175px;
            border: 4px solid #FFF;
            margin: 10px;
        }
        
        .follow {
            background-color:#FC563B;
            height: 80px;
            cursor:pointer;
        }
        
        .follow:hover {
            background-color:#F22F26;
            height: 80px;
            cursor:pointer;
        }
        
        .login_control {
            background-color:#FFF;
            padding:10px;
        }
        
        .control {
            color:#000;
            margin:10px;
        }
        
        .label {
            color: #EB4F26;
            font-size: 18px;
            font-weight: 500;
        }
        
        .form-control {
            color: #000000 !important;
            font-size: 25px;
            border: none;
            padding: 25px;
            padding-left: 10px;
            border-bottom: 1px solid #CCC;
            margin-bottom: 10px;
            outline: none;
            -webkit-box-shadow: none !important;
            -moz-box-shadow: none !important;
            box-shadow: none !important;
        }

        .form-control:focus {
            border-radius: 0px;
            border-bottom: 1px solid #FC563B;
            margin-bottom: 10px;
            outline: none;
            -webkit-box-shadow: none !important;
            -moz-box-shadow: none !important;
            box-shadow: none !important;
        }
        
        .btn-orange {
            background-color: #FC563B;
            border-radius: 0px;
            margin: 5px;
            padding: 5px;
            width: 150px;
            font-size: 20px;
            font-weight: inherit;
            color:#fff !important;
        }

        .btn-orange:hover {
            background-color: #F22F26;
            border-radius: 0px;
            margin: 5px;
            padding: 5px;
            width: 150px;
            font-size: 20px;
            font-weight: inherit;
            color:#fff !important;
        }
        
        .line {
            border-bottom : 2px solid #F32D27;
        }

        .outter {
            padding: 0px;
            border: 1px solid rgba(255, 255, 255, 0.29);
            border-radius: 50%;
            width: 200px;
            height: 200px;
            margin: 4px;
        }

        .vcenters {
            display: flex;
            align-items: center;            
        }
        
        .containesr {
            position: relative;
            height: 14rem;
            border: 1px solid;
        }
        
        .vcenter {
            position: absolute;
            top: 50%;
            left:50%;
            transform: translate(-50%,-50%);
        }        
    </style>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="container" role="main">
    	<div class="vcenter">
        	<div class="row">
        	    <div class="login_box">
            	    <div class="col-md-12 col-xs-12" align="center">
                        <div class="line"><h3><?= date( 'd/m/Y H.i.s' ) ?></h3></div>
                        <div class="outter">
                            <img src="http://img02.deviantart.net/4626/i/2014/339/5/8/redhead_girl___ballpoint_pen_by_vianaarts-d5531ab.jpg" class="image-circle"/>
                        </div>
                        <!--
                        <h1>Hi Guest</h1>
                        <span>INDIAN</span>
                        -->
            	    </div>
                    <div class="col-md-6 col-xs-6 follow line" align="center">
                        <h3>
                             125651 <br/> <span>FOLLOWERS</span>
                        </h3>
                    </div>
                    <div class="col-md-6 col-xs-6 follow line" align="center">
                        <h3>
                             125651 <br/> <span>FOLLOWERS</span>
                        </h3>
                    </div>
                    
                    <div class="col-md-12 col-xs-12 login_control">
                        <div class="control">
                            <div class="label">Email</div>
                            <input type="email" class="form-control" placeholder="email@email.com" autofocus/>
                        </div>
                        
                        <div class="control">
                             <div class="label">Password</div>
                            <input type="password" class="form-control" value=""/>
                        </div>
                        <div align="center">
                             <button class="btn btn-orange">LOGIN</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src='//code.jquery.com/jquery-3.1.1.min.js'></script>
    <script src='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' integrity='sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa' crossorigin='anonymous'></script>
 
  </body>
</html>
